# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TodoApplication' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'RealmSwift'

  target 'TodoApplicationTests' do
    inherit! :search_paths
    
    pod 'RealmSwift'
  end
  
  target 'TodoApplicationUITests' do
      inherit! :search_paths
      
      pod 'EarlGrey'
      pod 'RealmSwift'
  end

end
